### ISSUE TITLE
Resource: API Tokens

### ISSUE THREAD

**Issue by vknabel** [metal-stack-cloud/terraform-provider-metal#44]
We recently introduced API Tokens, although they are currently in early stages and have not been made publicly available.
Currently there is no possibility to create tokens for external users. Once this is public we should include them in the setup workflow of this provider.

- [ ] Resource `api_token`
- [x] Docs: how to get started with tokens (favored over console jwt)
- [ ] *Optional:* Data Source `api_tokens`

**Comment by simcod** [comment]
Postponed until requested.
