### ISSUE TITLE
Adapt to new config file structure

### ISSUE THREAD

**Issue by simcod** [metal-stack-cloud/terraform-provider-metal#80]
The structure of the `~/.metal-stack-cloud/config.yaml` changed. Defaults can currently not be derived anymore.

**Comment by Gerrit91** [comment]
The config should be used exclusively by the CLI from my point of view. Please create an own configuration file for this.

**Comment by simcod** [comment]
All right. We will work on this next week.

**Comment by vknabel** [comment]
If we do not reuse the same config, I'd remove the config file. In practice this might be confusing for users. Defaulting to env plus allowing direct override should be fine.
